//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordochka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id_employee { get; set; }
        public string surname_employee { get; set; }
        public string name_employee { get; set; }
        public string patronymic { get; set; }
        public string series { get; set; }
        public string numbers { get; set; }
        public string id_divisions { get; set; }
        public int id_gender { get; set; }
        public double payment { get; set; }
        public System.DateTime birthdate { get; set; }
        public int id_category { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
