//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordochka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> id_client_service { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
