//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordochka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mordochkaEntities : DbContext
    {
        public mordochkaEntities()
            : base("name=mordochkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Category_Product> Category_Product { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientService> ClientService { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EnterClient> EnterClient { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagClient> TagClient { get; set; }
        public virtual DbSet<Image_Product> Image_Product { get; set; }
        public virtual DbSet<Image_Service> Image_Service { get; set; }
    }
}
