//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordochka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_product { get; set; }
        public string name_product { get; set; }
        public int id_catprod { get; set; }
        public decimal cost { get; set; }
        public string property { get; set; }
        public string description { get; set; }
        public double weight { get; set; }
        public double size_width { get; set; }
        public double size_height { get; set; }
        public double size_length { get; set; }
        public string producer { get; set; }
        public Nullable<System.DateTime> start_date_producer { get; set; }
        public byte[] image { get; set; }
    
        public virtual Category_Product Category_Product { get; set; }
        public virtual Image_Product Image_Product { get; set; }
    }
}
